#!/usr/bin/env python3
"""Refresh all-time run totals from Strava into _data/strava_stats.yml.

Reads credentials from the environment -- never hardcode them here:

    STRAVA_CLIENT_ID
    STRAVA_CLIENT_SECRET
    STRAVA_REFRESH_TOKEN

Strava rotates the refresh token on every refresh and invalidates the old one,
so the new value has to be persisted or the next run fails. When running under
GitHub Actions this writes the rotated token to $GITHUB_OUTPUT (masked) for the
workflow to store back into the repository secret.
"""

import os
import sys
from datetime import date
from pathlib import Path

import requests

API = "https://www.strava.com/api/v3"
TOKEN_URL = "https://www.strava.com/oauth/token"
TIMEOUT = 30

M_PER_MI = 1609.34
M_PER_FT = 0.3048

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "_data" / "strava_stats.yml"


def env(name):
    value = os.environ.get(name)
    if not value:
        sys.exit(f"error: {name} is not set. See the docstring for the required variables.")
    return value


def refresh_access_token():
    """Exchange the refresh token for an access token.

    Returns (access_token, new_refresh_token).
    """
    resp = requests.post(
        TOKEN_URL,
        data={
            "client_id": env("STRAVA_CLIENT_ID"),
            "client_secret": env("STRAVA_CLIENT_SECRET"),
            "grant_type": "refresh_token",
            "refresh_token": env("STRAVA_REFRESH_TOKEN"),
        },
        timeout=TIMEOUT,
    )
    resp.raise_for_status()
    tokens = resp.json()
    return tokens["access_token"], tokens["refresh_token"]


def fetch_run_totals(access_token):
    """Return Strava's all-time run totals.

    Note the endpoint: athlete stats live under /athletes/{id}/stats. There is
    no /athlete/stats -- requesting it returns 404.
    """
    headers = {"Authorization": f"Bearer {access_token}"}

    me = requests.get(f"{API}/athlete", headers=headers, timeout=TIMEOUT)
    me.raise_for_status()
    athlete_id = me.json()["id"]

    stats = requests.get(f"{API}/athletes/{athlete_id}/stats", headers=headers, timeout=TIMEOUT)
    stats.raise_for_status()
    return stats.json()["all_run_totals"]


def persist_rotated_token(new_refresh_token):
    """Hand the rotated refresh token back to the workflow, if we're in one."""
    github_output = os.environ.get("GITHUB_OUTPUT")
    if not github_output:
        print(
            "note: refresh token was rotated. Update STRAVA_REFRESH_TOKEN in your "
            "local .env before the next run.",
            file=sys.stderr,
        )
        return

    # Mask before emitting so the value never appears in a build log.
    print(f"::add-mask::{new_refresh_token}")
    with open(github_output, "a", encoding="utf-8") as fh:
        fh.write(f"new_refresh_token={new_refresh_token}\n")


def write_stats(totals):
    miles = totals["distance"] / M_PER_MI
    hours = totals["moving_time"] / 3600
    feet = totals["elevation_gain"] / M_PER_FT

    # `updated` is emitted unquoted so Jekyll reads it as a date, matching the
    # convention in _data/races.yml.
    body = (
        "# Generated by scripts/update_strava_stats.py -- do not edit by hand.\n"
        "# All-time Strava run totals, rendered by _includes/run_stats.html.\n"
        f"updated: {date.today().isoformat()}\n"
        f"runs: {totals['count']}\n"
        f"distance_mi: {miles:.1f}\n"
        f"moving_time_hr: {hours:.1f}\n"
        f"elevation_gain_ft: {round(feet)}\n"
    )

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(body, encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    print(body, end="")


def main():
    access_token, new_refresh_token = refresh_access_token()
    if new_refresh_token != os.environ.get("STRAVA_REFRESH_TOKEN"):
        persist_rotated_token(new_refresh_token)
    write_stats(fetch_run_totals(access_token))


if __name__ == "__main__":
    main()
